name: Intégration Complète

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Install Jest and Babel dependencies
      run: |
        npm install --save-dev jest @babel/preset-env babel-jest ts-jest

    - name: Run tests
      run: npm test

  test-unitaire:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies for Test_unitaire_javascript
      run: |
        npm install

    - name: Run unit tests
      run: npm test
