name: Generate JSDoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Vérifie le code source du dépôt

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        # Remplacez '14' par la version de Node.js que vous utilisez

    - name: Install JSDoc
      run: npm install -g jsdoc
      # Installe JSDoc

    - name: Generate Documentation
      run: jsdoc -c jsdoc.json
      # Génère la documentation en utilisant votre fichier de configuration JSDoc

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
